### ISSUE TITLE
pixellink_eval.py

### ISSUE THREAD

**Issue by niddal-imam** [opconty/pixellink_keras#2]
Hi,

When I run the code, I got this error massage: 
 File "pixellink_eval.py", line 27
    image, *r = resize_image(image)
           ^
SyntaxError: invalid syntax

When I remove the *, I got this error massage: 
image, r = resize_image(image)
ValueError: too many values to unpack

Any suggestions.

Thanks

**Comment by opconty** [comment]
Hi
This method returns three values , namely, im, ratio_h, ratio_w.

**Comment by niddal-imam** [comment]
Hi,

Thanks for your answer. However, when I run the code, I got an error because of *r=resize_image(image)

**Comment by opconty** [comment]
HI.
make sure your python version, maybe that's the crux. I don't have this error in my python3.6

**Comment by niddal-imam** [comment]
Thanks, I was using python 2.
