### ISSUE TITLE
Python2 Vs Python 3 

### ISSUE THREAD

**Issue by AlbinDavid** [opconty/pixellink_keras#4]
https://github.com/opconty/pixellink_keras/blob/3a1b48e76b78defbe5da6b1872213fd08af6fe98/pixellink_utils.py#L83

zip will not return a list in python3

**Comment by opconty** [comment]
`list(zip(*np.where(pixel_mask)) )`

yep, it's a generator

**Comment by AlbinDavid** [comment]
yes list(zip(*np.where(pixel_mask))) works.
